name: Build Rust WASM

on:
  push:
    branches: [ main, rust_wasm ]
    paths:
      - 'rust-game/**'
      - '.github/workflows/build-rust-wasm.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'rust-game/**'
      - '.github/workflows/build-rust-wasm.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          rust-game/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('rust-game/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build Rust WASM module
      run: |
        cd rust-game
        wasm-pack build --target web --out-dir pkg
        
    - name: Verify build artifacts
      run: |
        ls -la rust-game/pkg/
        echo "✅ WASM build completed successfully!"
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust-wasm-build
        path: |
          rust-game/pkg/*.wasm
          rust-game/pkg/*.js
          rust-game/pkg/*.ts
          rust-game/pkg/package.json
        retention-days: 30
        
